racetime:
  api:
    base-url: https://racetime.gg
    websocket-base: wss://racetime.gg

spring:
  http:
    converters:
      preferred-json-mapper: gson

logging:
  level:
    root: INFO
    de:
      scaramangado: INFO
  file:
    name: race-announcer.log
    max-history: 15
