version: '3.9'
services:
  race-announcer:
    image: ghcr.io/scaramangado/rtgg-race-announcer/race-announcer:latest
    container_name: race-announcer
    volumes:
      - ~/docker-volumes/race-announcer:/etc/announcer
    restart: unless-stopped
    networks:
      - announcer

networks:
  announcer:
